SELECT D.NAME AS Department, E.NAME AS Employee, SALARY AS Salary
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
WHERE E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E2.DEPARTMENTID = E.DEPARTMENTID  # 외부 Employee랑 비교
)