(SELECT NAME AS results
FROM USERS U
JOIN MOVIERATING R ON U.USER_ID = R.USER_ID
GROUP BY U.USER_ID
ORDER BY COUNT(*) DESC, U.NAME ASC
LIMIT 1)
UNION ALL
(SELECT TITLE AS results
FROM MOVIES M
JOIN MOVIERATING R ON M.MOVIE_ID = R.MOVIE_ID
WHERE R.CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY M.MOVIE_ID
ORDER BY AVG(RATING) DESC, M.TITLE ASC
LIMIT 1);