SELECT NAME AS CUSTOMERS
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.ID = ORDERS.CUSTOMERID
WHERE ORDERS.CUSTOMERID IS NULL

-- SELECT NAME AS CUSTOMERS
-- FROM CUSTOMERS
-- WHERE ID NOT IN (SELECT DISTINCT CUSTOMERID FROM ORDERS)