# Write your MySQL query statement below
SELECT NAME AS CUSTOMERS
FROM CUSTOMERS
WHERE ID NOT IN (SELECT CUSTOMERID FROM ORDERS)
-- SELECT C.NAME AS CUSTOMERS
-- FROM CUSTOMERS C
-- LEFT JOIN ORDERS O ON C.ID=O.CUSTOMERID
-- WHERE O.ID IS NULL;