SELECT ROUND(COUNT(A2.player_id) * 1.0 / (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY), 2) AS fraction
FROM (
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_DATE
    FROM ACTIVITY
    GROUP BY PLAYER_ID
) A1
LEFT JOIN ACTIVITY A2 ON A1.PLAYER_ID = A2.PLAYER_ID
WHERE A2.EVENT_DATE = DATE_ADD(A1.FIRST_DATE, INTERVAL 1 DAY) AND A2.GAMES_PLAYED >= 1;